Update conexao

diff --git a/Sistema/conexao b/Sistema/conexao
--- a/Sistema/conexao
+++ b/Sistema/conexao
@@ -641,7 +641,7 @@ SCOLOR='\033[0m'
     }
 	inst_ssl() {
 		if netstat -nltp | grep 'stunnel4' 1>/dev/null 2>/dev/null; then
-			[[ $(netstat -nltp | grep 'stunnel4' | wc -l) != '0' ]] && sslt=$(netstat -nplt | grep stunnel4 | awk {'print $4'} | awk -F ":" {'print $2'} | xargs) || sslt="\033[1;31mINDISPONIVEL"
+			[[ $(netstat -nltp | grep 'stunnel4' | wc -l) != '0' ]] && sslt=$(netstat -nplt | grep stunnel4 | awk {'print $4'} | awk -F ":" {'print $2'} | xargs) || sslt="\033[1;31mAVAILABLE"
 			echo -e "\E[44;1;37m              GENERATE SSL TUNNEL               \E[0m"
 			echo -e "\n\033[1;33mPORT\033[1;37m: \033[1;32m$sslt"
 			echo ""
@@ -664,22 +664,22 @@ SCOLOR='\033[0m'
 					fun_conexao
 				}
 				verif_ptrs $porta
-				echo -e "\033[1;32mALTERANDO PORTA SSL TUNNEL!"
+				echo -e "\033[1;32mALTERING THE SSL TUNNEL PORT!"
 				var2=$(grep 'accept' /etc/stunnel/stunnel.conf | awk '{print $NF}')
 				sed -i "s/\b$var2\b/$porta/g" /etc/stunnel/stunnel.conf >/dev/null 2>&1
 				echo ""
 				fun_bar 'sleep 2'
 				echo ""
-				echo -e "\033[1;32mREINICIANDO SSL TUNNEL!\n"
+				echo -e "\033[1;32mRESTART SSL TUNNEL!\n"
 				fun_bar 'service stunnel4 restart' '/etc/init.d/stunnel4 restart'
 				echo ""
-				netstat -nltp | grep 'stunnel4' >/dev/null && echo -e "\033[1;32mPORTA ALTERADA COM SUCESSO !" || echo -e "\033[1;31mERRO INESPERADO!"
+				netstat -nltp | grep 'stunnel4' >/dev/null && echo -e "\033[1;32mPORT CHANGED SUCCESSFULLY !" || echo -e "\033[1;31mUNEXPECTED ERROR!"
 				sleep 3.5s
 				clear
 				fun_conexao
 			}
 			[[ "$resposta" = '2' ]] && {
-				echo -e "\033[1;32mREMOVENDO O  SSL TUNNEL !\033[0m"
+				echo -e "\033[1;32mREMOVING THE SSL TUNNEL !\033[0m"
 				del_ssl() {
 					service stunnel4 stop
 					apt-get remove stunnel4 -y
@@ -692,23 +692,23 @@ SCOLOR='\033[0m'
 				echo ""
 				fun_bar 'del_ssl'
 				echo ""
-				echo -e "\033[1;32mSSL TUNNEL REMOVIDO COM SUCESSO!\033[0m"
+				echo -e "\033[1;32mSSL TUNNEL SUCCESSFULLY REMOVED!\033[0m"
 				sleep 3
 				fun_conexao
 			} || {
-				echo -e "\033[1;31mRetornando...\033[0m"
+				echo -e "\033[1;31mReturning...\033[0m"
 				sleep 3
 				fun_conexao
 			}
 		else
 			clear
-			echo -e "\E[44;1;37m              INSTALAR SSL TUNNEL               \E[0m"
+			echo -e "\E[44;1;37m              INSTALL SSL TUNNEL               \E[0m"
 			echo ""
-			echo -e "\033[1;31m[\033[1;36m1\033[1;31m] \033[1;37m• \033[1;33mINSTALAR SSL TUNNEL PADRÃO\033[0m"
-			echo -e "\033[1;31m[\033[1;36m2\033[1;31m] \033[1;37m• \033[1;33mINSTALAR SSL TUNNEL WEBSOCKET\033[0m"
-			echo -e "\033[1;31m[\033[1;36m0\033[1;31m] \033[1;37m• \033[1;33mVOLTAR\033[0m"
+			echo -e "\033[1;31m[\033[1;36m1\033[1;31m] \033[1;37m• \033[1;33mINSTALL DEFAULT SSL TUNNEL\033[0m"
+			echo -e "\033[1;31m[\033[1;36m2\033[1;31m] \033[1;37m• \033[1;33mINSTALL SSL TUNNEL WEBSOCKET\033[0m"
+			echo -e "\033[1;31m[\033[1;36m0\033[1;31m] \033[1;37m• \033[1;33mTO GO BACK\033[0m"
 			echo ""
-			echo -ne "\033[1;32mOQUE DESEJA FAZER \033[1;33m?\033[1;37m "
+			echo -ne "\033[1;32mWHAT DO YOU WANT TO DO \033[1;33m?\033[1;37m "
 			read resposta
 			echo ""
             if [[ "$resposta" = '1' ]]; then
@@ -716,44 +716,44 @@ SCOLOR='\033[0m'
             elif [[ "$resposta" = '2' ]]; then     
                 portssl='80'
             elif [[ "$resposta" = '0' ]]; then
-				echo -e "\033[1;31mRetornando...\033[0m"
+				echo -e "\033[1;31mReturning...\033[0m"
 				sleep 3
 				fun_conexao
             else
 			echo ""
-			echo -e "\033[1;31mOpcao invalida !\033[0m"
+			echo -e "\033[1;31mInvalid option !\033[0m"
 			sleep 1
 			inst_ssl
 		fi
             clear
 			echo -e "\E[44;1;37m           INSTALADOR SSL TUNNEL             \E[0m"
-			echo -e "\n\033[1;33mVC ESTA PRESTES A INSTALAR O SSL TUNNEL !\033[0m"
+			echo -e "\n\033[1;33mYOU ARE ABOUT TO INSTALL SSL TUNNEL !\033[0m"
 			echo ""
-			echo -ne "\033[1;32mDESEJA CONTINUAR \033[1;31m? \033[1;33m[s/n]:\033[1;37m "
+			echo -ne "\033[1;32mDO YOU WISH TO CONTINUE \033[1;31m? \033[1;33m[s/n]:\033[1;37m "
 			read resposta
 			[[ "$resposta" = 's' ]] && {
-				echo -e "\n\033[1;33mDEFINA UMA PORTA PARA O SSL TUNNEL !\033[0m"
+				echo -e "\n\033[1;33mSPECIFY A PORT FOR THE TLS TUNNEL !\033[0m"
 				echo ""
-				echo -ne "\033[1;32mQUAL PORTA DESEJA ULTILIZAR \033[1;33m?\033[1;37m "
+				echo -ne "\033[1;32mWHICH PORT DO YOU WANT TO USE \033[1;33m?\033[1;37m "
                 read porta
 				[[ -z "$porta" ]] && {
 					echo ""
-					echo -e "\033[1;31mPorta invalida!"
+					echo -e "\033[1;31mInvalid Port!"
 					sleep 3
 					clear
 					fun_conexao
 				}
 				verif_ptrs $porta
-				echo -e "\n\033[1;32mINSTALANDO O SSL TUNNEL !\033[1;33m"
+				echo -e "\n\033[1;32mINSTALLING SSL TUNNEL !\033[1;33m"
 				echo ""
 				fun_bar 'apt-get update -y' 'apt-get install stunnel4 -y'
-				echo -e "\n\033[1;32mCONFIGURANDO O SSL TUNNEL !\033[0m"
+				echo -e "\n\033[1;32mCONFIGURING THE SSL TUNNEL !\033[0m"
 				echo ""
 				ssl_conf() {
 					echo -e "cert = /etc/stunnel/stunnel.pem\nclient = no\nsocket = a:SO_REUSEADDR=1\nsocket = l:TCP_NODELAY=1\nsocket = r:TCP_NODELAY=1\n\n[stunnel]\nconnect = 127.0.0.1:$portssl\naccept = ${porta}" >/etc/stunnel/stunnel.conf
 				}
 				fun_bar 'ssl_conf'
-				echo -e "\n\033[1;32mCRIANDO CERTIFICADO !\033[0m"
+				echo -e "\n\033[1;32mCREATING CERTIFICATE !\033[0m"
 				echo ""
 				ssl_certif() {
 					#crt='EC'
@@ -770,10 +770,10 @@ SCOLOR='\033[0m'
 					#cat cert.pem key.pem >>/etc/stunnel/stunnel.pem
 					#rm key.pem cert.pem >/dev/null 2>&1
 					sed -i 's/ENABLED=0/ENABLED=1/g' /etc/default/stunnel4
-					cd /etc/stunnel && wget https://raw.githubusercontent.com/rodrigo12xd/SSHPLUS/master/Sistema/script/stunnel.pem && cd $HOME
+					cd /etc/stunnel && wget https://raw.githubusercontent.com/kumultricks/KumulSSH/master/Sistema/script/stunnel.pem && cd $HOME
 				}
 				fun_bar 'ssl_certif'
-				echo -e "\n\033[1;32mINICIANDO O SSL TUNNEL !\033[0m"
+				echo -e "\n\033[1;32mSTARTING SSL TUNNEL !\033[0m"
 				echo ""
 				fun_finssl() {
 					service stunnel4 restart
@@ -781,12 +781,12 @@ SCOLOR='\033[0m'
 					/etc/init.d/stunnel4 restart
 				}
 				fun_bar 'fun_finssl' 'service stunnel4 restart'
-				echo -e "\n\033[1;32mSSL TUNNEL INSTALADO COM SUCESSO !\033[1;31m PORTA: \033[1;33m$porta\033[0m"
+				echo -e "\n\033[1;32mSSL TUNNEL INSTALLED SUCCESSFULLY !\033[1;31m PORT: \033[1;33m$porta\033[0m"
 				sleep 3
 				clear
 				fun_conexao
 			} || {
-				echo -e "\n\033[1;31mRetornando...\033[0m"
+				echo -e "\n\033[1;31mReturning...\033[0m"
 				sleep 2
 				clear
 				fun_conexao
@@ -796,16 +796,16 @@ SCOLOR='\033[0m'
 
 	fun_openvpn() {
 		if readlink /proc/$$/exe | grep -qs "dash"; then
-			echo "Este script precisa ser executado com bash, não sh"
+			echo "This script needs to be run with bash, not sh"
 			exit 1
 		fi
 		[[ "$EUID" -ne 0 ]] && {
 			clear
-			echo "Execulte como root"
+			echo "Execulte with root"
 			exit 2
 		}
 		[[ ! -e /dev/net/tun ]] && {
-			echo -e "\033[1;31mTUN TAP NAO DISPONIVEL\033[0m"
+			echo -e "\033[1;31mTUN TAP NOT AVAILABLE\033[0m"
 			sleep 2
 			exit 3
 		}
